# Generated by Django 5.0.7 on 2024-07-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="faculty name",
                        max_length=255,
                        unique=True,
                        verbose_name="faculty",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "faculties",
                "ordering": ["name"],
            },
        ),
    ]
