# Generated by Django 5.0.7 on 2024-07-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="faculty",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
