# Generated by Django 5.0.7 on 2024-07-31 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculties", "0002_faculty_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faculty",
            name="name",
            field=models.CharField(
                help_text="faculty name",
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        4, "name of the faculty should not be less than 4 characters"
                    )
                ],
                verbose_name="faculty",
            ),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, blank=True, max_length=255, null=True, unique=True
            ),
        ),
    ]
